### PR TITLE
Update dependencies to fix vulnerabilities

### PR DESCRIPTION
**Pull request by SirJackovich**
Do I need to update the pin to make a release? 
What is the best way to test these changes? I can't get the tests to run locally.

https://npmjs.com/advisories/118
https://npmjs.com/advisories/146
https://npmjs.com/advisories/157
https://npmjs.com/advisories/525
https://npmjs.com/advisories/534
https://npmjs.com/advisories/566
https://npmjs.com/advisories/577
https://npmjs.com/advisories/578
https://npmjs.com/advisories/606
https://npmjs.com/advisories/612
https://npmjs.com/advisories/646
https://npmjs.com/advisories/664
https://npmjs.com/advisories/755
https://npmjs.com/advisories/782
https://npmjs.com/advisories/786
https://npmjs.com/advisories/788
https://npmjs.com/advisories/803
https://npmjs.com/advisories/813
https://npmjs.com/advisories/886

### CODE REVIEW

**Comment by redbugz** [comment]
If you look at the tests, you'll see that the new version of chokidar uses new ES6 features and doesn't work with Node 4 like the tests use

**Comment by redbugz** [comment]
Updating gulp from 3 -> 4 is a big jump, I would expect that to require some code changes

**Comment by SirJackovich** [comment]
Cool, how do I fix it? Does this repo need to support node 4?

**Comment by joeycozza** [comment]
I would think yes, this repo needs node 4 support to handle the old search app that is still using node 4.

Easiest way to "fix" it would be to go back to the old version of chokidar.

**Comment by SirJackovich** [comment]
The search app that is on node 4 does not use this.

**Comment by joeycozza** [comment]
closing due to low priority, staleness, and ci not passing.

**Pull request closed without merging**
