### PR TITLE
Update dependency to fix vulnerability

### PR DESCRIPTION
**Pull request by SirJackovich**
https://www.npmjs.com/advisories/118

### CODE REVIEW

**Comment by redbugz** [comment]
Have you run this against a project yet? Minimatch updates sometimes cause the globs to resolve differently on the files.

**Comment by SirJackovich** [comment]
I have not

**Comment by redbugz** [comment]
if you have a project that uses this, can you try it pinned to this branch and see if it still seems to create the assemblies correctly?

**Comment by SirJackovich** [comment]
yes

**Comment by SirJackovich** [comment]
I am making a new pr with more changes

**Pull request closed without merging**
